updated twitter link
KMPARDS/recycle-dapp-website pull request #2
Opened 2020-04-25 06:31 UTC by Sanket403

updated twitter link

2020-04-25 16:28 UTC, zemse requested changes
@Sanket403 It would be really better if social page links open in a new tab.

2020-05-15 14:26 UTC, kavimrvavi submitted a review, later dismissed

2020-05-26 12:16 UTC, vikashkmpards approved these changes

2020-05-26 12:23 UTC, kavimrvavi approved these changes

2020-06-25 07:52 UTC, maheshrapelli141 approved these changes

2020-06-25 08:21 UTC, zemse approved these changes

2020-06-25 08:21 UTC, merged